### ISSUE TITLE
Allow loading of the extended battle goals

### ISSUE THREAD

**Issue by Sebaestschjin** [Sebaestschjin/gloomhaven-campaign-manager#26]
The current Gloomhaven mod doesn't contain the [extended Battle Goals](https://steamcommunity.com/sharedfiles/filedetails/?id=1709870064) from the community. It would be nice to have an option that enables loading them by creating a deck from the image file. Have to check with the mod's author if he's okay with that usage.

**Comment by asphaltbuffet** [comment]
+1 for this
