### ISSUE TITLE
Migrate enhanced abilities into new character envelopes

### ISSUE THREAD

**Issue by WMSkyfall** [Sebaestschjin/gloomhaven-campaign-manager#64]
Our Mindthief retired recently in my regular group, and I successfully tested a process for baking her enhanced cards into all future Mindthief boxes. (Pull a fresh Mindthief from the template envelope, replace its ability cards with the enhanced cards, reset the Mindthief envelope, drop the altered Mindthief box into the now-empty envelope.) It would be nice for the campaign manager to be able to populate the character template envelopes on load with enhanced versions of the classes' ability cards, both for classes in active play and for inactive/retired characters.

My current workaround is to import the altered envelopes into a fresh copy of the mod as a Saved Object. This works for now, but I'm curious about whether this process could be automated in the campaign manager, given that it's already storing enhancement data for active characters.

**Comment by Sebaestschjin** [comment]
Yeah, I was thinking about changing the enhancement loading process and get rid of the waiting (which sucks, as you already found out :-)) by simply replacing the character box instead of adding the stickers after everything is done.
