### ISSUE TITLE
Include notebook data in save

### ISSUE THREAD

**Issue by asphaltbuffet** [Sebaestschjin/gloomhaven-campaign-manager#70]
Our group uses the TTS notebooks to record progress on personal goals, plans for future enhancements, etc. It would be really nice to have this persist along with the saved data. Maybe also the options notebook so the values don't have to be reset when importing into a new game.

**Comment by Sebaestschjin** [comment]
Good point. Do you have other notebook as as well or one per player? Options might be tricky. Simply saving and loading would be easy. But if a newer mod version has new options those would be overwritten. I'll have to think of something. :-)

**Comment by asphaltbuffet** [comment]
Just one notebook per player. Not renamed from default colors.

Options point is good. Maybe it gets saved but not loaded into options
notebook? That way it's at least in the game for reference.

**Comment by Sebaestschjin** [comment]
Yeah, good idea. It could create a new notebook "Previous Options" or something which can be checked. This would be very simple to implement, so I guess I'll start from there. :-)
