### ISSUE TITLE
Support gloomhaven scenario tree

### ISSUE THREAD

**Issue by asphaltbuffet** [Sebaestschjin/gloomhaven-campaign-manager#71]
It would be great if saving also created a notebook page with data in the format to use with Gloomhaven Scenario Tree (https://dmungin.github.io/gloomhaven-scenario-tree-ng/).

**Comment by Sebaestschjin** [comment]
Thanks for the link, this looks cool. I'll look it into how the data is required, but I guess that should be doable.
