### ISSUE TITLE
Save which ability cards are in hand

### ISSUE THREAD

**Issue by asphaltbuffet** [Sebaestschjin/gloomhaven-campaign-manager#72]
When loading cards, player ability cards are not in the same hand (primary and secondary. Players then need to remember which cards were replaced during leveling up. This can be tedious for high-level characters.

**Comment by Sebaestschjin** [comment]
Yes, this is already planned with #25. It's the next thing I'll do. :-) Just a question: How do you use the secondary hand? My current plan was to save all abilities from the primary hand. During load the primary hand is restored and all other abilities are moved to the secondary hand. That's how I use the hands. Or do you maybe use the secondary hand for active abilities, too? Then maybe it would Elbe required to save the contents of both hands.

**Comment by asphaltbuffet** [comment]
We use primary hand for cards in the scenario, secondary hand for cards
that are available to use but not active. Song it shorter way, if I level
up and put a new card in active hand, then the replaced card would go in
the secondary hand in case I want to swap it later for a different
scenario.

I think that's how you're using it from your description too.
