### ISSUE TITLE
Load issues with gaps in party

### ISSUE THREAD

**Issue by xexuxjy** [Sebaestschjin/gloomhaven-campaign-manager#76]
A relatively minor issue, but  I found a bug in our normal campaign game. Our normal character layout has slots 0 and 1 filled, 2 empty and 3 filled. When saving the data all characters are saved to the json file. On loading the save it stops loading characters the first time it hits a null, despite the fact there is a character after that. (Hand editing the json to move the null to the end of the collection restored the missing character though obviously in slot 2).

Very useful utility, thankyou.

**Comment by Sebaestschjin** [comment]
Thanks for the find! I recently changed how empty slots are handled, guess I forgot to test that fully... Will fix that with the next version.
