### ISSUE TITLE
Many player hands are created when loading

### ISSUE THREAD

**Issue by alepocalypse** [Sebaestschjin/gloomhaven-campaign-manager#81]
https://i.imgur.com/J6s65OV.png

Brand new game of Gloomhaven, additive load the manager and 8 player zones load in the middle of the table (seen in pic)

These are only visible cause I had the tool selected. Normally, they'd just sit, invisibly, and mess with cards as you try and move them around.

i can do a workaround and delete them myself, but I know others out there will just hit a wall. These hand zones make GH unplayable as they overlap the card selection area for player 2 + 3

**Comment by Sebaestschjin** [comment]
Interesting, never noticed that before. Don't know what I changed to make that happen or if that was always the case or if its because of the TTS update a while ago. I removed the handzone from my mod now, so they won't load again.
Thanks for the report.
